import re
balance=53.44
nombre="Juan Perez"
print("Hola %s, tu balance es de %.2f$"%(nombre,balance))
balance=str(balance)
type(balance)
balance.__len__()
balance=bool(balance)
type(balance)
balance=int(balance)
type(balance)
str(balance).__len__()
balance=float(balance)
type(balance)
str(balance).__len__()
ej="                    Esto es un string de ejemplo"
x=ej.lstrip()
print(x)
x=x.split(x,4)
print(x)
x=ej.lstrip()
x=x.lower()
print(x)
x=x.upper()
print(x)
x=ej.lstrip()
x=x.find("ejemplo")
print(x)
x=ej.lstrip()
x=x.index("ejemplo")
print(x)
x=ej.lstrip()
x=x.startswith("Esto")
print(x)
r1=re.findall("a","En un lugar de la Mancha, de cuyo nombre no quiero acordarme, no ha mucho que vivía un hidalgo de los de lanza en astillero, adarga antigua, rocín flaco y galgo corredor")
r1.__len__()